# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: siamese.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsiamese.proto\x12\x07siamese\".\n\tEmbedding\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x11\n\tclient_id\x18\x02 \x01(\t\"_\n\rEmbeddingPair\x12&\n\nembedding1\x18\x01 \x01(\x0b\x32\x12.siamese.Embedding\x12&\n\nembedding2\x18\x02 \x01(\x0b\x32\x12.siamese.Embedding\"b\n\x12SimilarityResponse\x12\x10\n\x08\x64istance\x18\x01 \x01(\x02\x12\x12\n\nis_similar\x18\x02 \x01(\x08\x12\x12\n\nclient1_id\x18\x03 \x01(\t\x12\x12\n\nclient2_id\x18\x04 \x01(\t2Z\n\x0eSiameseService\x12H\n\x11\x43ompareSimilarity\x12\x16.siamese.EmbeddingPair\x1a\x1b.siamese.SimilarityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'siamese_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMBEDDING']._serialized_start=26
  _globals['_EMBEDDING']._serialized_end=72
  _globals['_EMBEDDINGPAIR']._serialized_start=74
  _globals['_EMBEDDINGPAIR']._serialized_end=169
  _globals['_SIMILARITYRESPONSE']._serialized_start=171
  _globals['_SIMILARITYRESPONSE']._serialized_end=269
  _globals['_SIAMESESERVICE']._serialized_start=271
  _globals['_SIAMESESERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
