# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import siamese_pb2 as siamese__pb2


class SiameseServiceStub(object):
    """Serviço para comparação de similaridade
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompareSimilarity = channel.unary_unary(
                '/siamese.SiameseService/CompareSimilarity',
                request_serializer=siamese__pb2.EmbeddingPair.SerializeToString,
                response_deserializer=siamese__pb2.SimilarityResponse.FromString,
                )


class SiameseServiceServicer(object):
    """Serviço para comparação de similaridade
    """

    def CompareSimilarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiameseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompareSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareSimilarity,
                    request_deserializer=siamese__pb2.EmbeddingPair.FromString,
                    response_serializer=siamese__pb2.SimilarityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'siamese.SiameseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SiameseService(object):
    """Serviço para comparação de similaridade
    """

    @staticmethod
    def CompareSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/siamese.SiameseService/CompareSimilarity',
            siamese__pb2.EmbeddingPair.SerializeToString,
            siamese__pb2.SimilarityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
