# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iris_ping_pong.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'iris_ping_pong.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14iris_ping_pong.proto\x12\x10irispingponggprc\"(\n\nFitRequest\x1a\x1a\n\x07NDArray\x12\x0f\n\x07ndarray\x18\x01 \x01(\x0c\"%\n\x0b\x46itResponse\x12\x16\n\x0e\x66itResponseMsg\x18\x02 \x01(\t\"%\n\x0ePredictRequest\x12\x13\n\x0bpredRequest\x18\x03 \x01(\t\"\'\n\x0fPredictResponse\x12\x14\n\x0cpredResponse\x18\x04 \x01(\t2\xc8\x01\n\x0cIrisPingPong\x12U\n\x14GetServerResponseFit\x12\x1c.irispingponggprc.FitRequest\x1a\x1d.irispingponggprc.FitResponse\"\x00\x12\x61\n\x18GetServerResponsePredict\x12 .irispingponggprc.PredictRequest\x1a!.irispingponggprc.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iris_ping_pong_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FITREQUEST']._serialized_start=42
  _globals['_FITREQUEST']._serialized_end=82
  _globals['_FITREQUEST_NDARRAY']._serialized_start=56
  _globals['_FITREQUEST_NDARRAY']._serialized_end=82
  _globals['_FITRESPONSE']._serialized_start=84
  _globals['_FITRESPONSE']._serialized_end=121
  _globals['_PREDICTREQUEST']._serialized_start=123
  _globals['_PREDICTREQUEST']._serialized_end=160
  _globals['_PREDICTRESPONSE']._serialized_start=162
  _globals['_PREDICTRESPONSE']._serialized_end=201
  _globals['_IRISPINGPONG']._serialized_start=204
  _globals['_IRISPINGPONG']._serialized_end=404
# @@protoc_insertion_point(module_scope)
